version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    resource_class: medium
    steps:
      - run: apk update
      - run: apk add git alpine-sdk gettext gettext-dev autoconf libtool automake po4a doxygen
      - run: git clone https://git.tukaani.org/xz.git .
      - run: git checkout v5.6.1
      - run: ./autogen.sh
      - run: ./configure
      - run:
          name: Reveal `$build`
          command: grep ^build= ./config.status | head -n 1 || true
      - run:
          name: Run the suspicious branching against the revealed `$build`
          command: |
            # https://www.openwall.com/lists/oss-security/2024/03/29/4/1
            eval `grep ^build=\'x86_64 config.status`
            if ! (echo "$build" | grep -Eq "^x86_64" > /dev/null 2>&1) && (echo "$build" | grep -Eq "linux-gnu$" > /dev/null 2>&1);then
                echo Safe
            else
                echo Unsafe
            fi
